export const AGENT_WORKFLOW_STEPS = [
  {
    id: "system-detection",
    title: "System Detection",
    description: "Erkennt automatisch, welches System (z. B. Jira Cloud, Asana, Azure DevOps) hinter einer angegebenen URL steckt und welche API-Version verfügbar ist.",
    phase: "System Detection",
    agentType: "system-detection",
    color: "sky",
  },
  {
    id: "auth-flow",
    title: "Authentication",
    description: "Leitet anhand des erkannten Systems den passenden Authentifizierungsprozess ein (API Token, OAuth2, Basic Auth etc.) und prüft die Berechtigungen.",
    phase: "Authentication",
    agentType: "auth-flow",
    color: "violet",
  },
  {
    id: "schema-discovery",
    title: "Source Discovery",
    description: "Findet automatisch die API-Spezifikation, analysiert Entities, Endpunkte, Auth, Pagination und Limits über autonome httpClient-Probes.",
    phase: "Source Discovery",
    agentType: "schema-discovery",
    color: "emerald",
  },
  {
    id: "target-schema",
    title: "Target Discovery",
    description: "Analysiert das Zielsystem und identifiziert, wie dessen Felder und Strukturen aufgebaut sind.",
    phase: "Target Discovery",
    agentType: "target-schema",
    color: "amber",
  },
  {
    id: "data-staging",
    title: "Data Staging",
    description: "Ordnet die erkannten Datenfelder des Quellsystems dem Zielsystem zu und bereitet die Daten für den Transfer vor.",
    phase: "Data Staging",
    agentType: "data-staging",
    color: "rose",
  },
  {
    id: "mapping-verification",
    title: "Mapping Verification",
    description: "Überprüft die definierten Mapping-Regeln auf Vollständigkeit und Konsistenz bezüglich der Quell- und Zielsysteme.",
    phase: "Mapping Verification",
    agentType: "mapping-verification",
    color: "sky",
  },
  {
    id: "quality-enhancement",
    title: "Quality Enhancement",
    description: "Optimiert die Datenqualität durch KI-gestützte Veredelungen wie Übersetzung, Zusammenfassung oder PII-Schwärzung basierend auf den konfigurierten Regeln.",
    phase: "Quality Enhancement",
    agentType: "quality-enhancement",
    color: "violet",
  },
  {
    id: "data-transfer",
    title: "Data Transfer",
    description: "Führt die eigentliche Datenmigration aus, orchestriert Requests, Batch-Verarbeitung und Error-Recovery.",
    phase: "Data Transfer",
    agentType: "data-transfer",
    color: "emerald",
  },
  {
    id: "verification",
    title: "Verification",
    description: "Prüft, ob alle Objekte korrekt und vollständig im Zielsystem angekommen sind, und erstellt einen Abweichungsreport.",
    phase: "Verification",
    agentType: "verification",
    color: "amber",
  },
  {
    id: "report",
    title: "Report",
    description: "Dokumentiert jede Aktion, API-Request und Datenveränderung revisionssicher für Nachvollziehbarkeit und erstellt einen finalen Report.",
    phase: "Report",
    agentType: "report",
    color: "rose",
  },
] as const;
