export const AGENT_WORKFLOW_STEPS = [
  {
    id: "system-detection",
    title: "System Detection Agent",
    description: "Erkennt automatisch, welches System (z. B. Jira Cloud, Asana, Azure DevOps) hinter einer angegebenen URL steckt und welche API-Version verfügbar ist.",
    phase: "Detection",
    agentType: "system-detection",
    color: "sky",
  },
  {
    id: "auth-flow",
    title: "Auth Flow Agent",
    description: "Leitet anhand des erkannten Systems den passenden Authentifizierungsprozess ein (API Token, OAuth2, Basic Auth etc.) und prüft die Berechtigungen.",
    phase: "Authentication",
    agentType: "auth-flow",
    color: "violet",
  },
  {
    id: "schema-discovery",
    title: "Capability Discovery Agent",
    description:
      "Findet automatisch die API-Spezifikation, analysiert Entities, Endpunkte, Auth, Pagination und Limits über autonome httpClient-Probes.",
    phase: "Source Schema",
    agentType: "schema-discovery",
    color: "emerald",
  },
  {
    id: "model-mapping",
    title: "Model Mapping Agent",
    description: "Ordnet die erkannten Datenfelder des Quellsystems dem Celion-Meta-Modell zu, um eine standardisierte interne Repräsentation zu erzeugen.",
    phase: "Model Mapping",
    agentType: "model-mapping",
    color: "amber",
  },
  {
    id: "target-schema",
    title: "Target Schema Agent",
    description: "Analysiert das Zielsystem (z. B. Asana) und identifiziert, wie dessen Felder mit dem Celion-Meta-Modell kompatibel sind.",
    phase: "Target Schema",
    agentType: "target-schema",
    color: "rose",
  },
  {
    id: "mapping-suggestion",
    title: "Mapping Suggestion Agent",
    description: "Erstellt ein initiales Feld-zu-Feld-Mapping (Source → Target) basierend auf Ähnlichkeit, Bezeichnung, Typ und Kontext der Daten.",
    phase: "Mapping",
    agentType: "mapping-suggestion",
    color: "sky",
  },
  {
    id: "consistency-validation",
    title: "Consistency & Validation Agent",
    description: "Überprüft das vorgeschlagene Mapping auf Typinkonsistenzen, Pflichtfelder und mögliche Datenverluste.",
    phase: "Validation",
    agentType: "consistency-validation",
    color: "violet",
  },
  {
    id: "dry-run",
    title: "Dry-Run Agent",
    description: "Führt eine Simulation der Migration durch (ohne zu schreiben), um Fehler, leere Felder oder API-Limits frühzeitig zu erkennen.",
    phase: "Dry-Run",
    agentType: "dry-run",
    color: "emerald",
  },
  {
    id: "data-transfer",
    title: "Data Transfer Agent",
    description: "Führt die eigentliche Datenmigration aus, orchestriert Requests, Batch-Verarbeitung und Error-Recovery.",
    phase: "Transfer",
    agentType: "data-transfer",
    color: "amber",
  },
  {
    id: "verification",
    title: "Verification Agent",
    description: "Prüft, ob alle Objekte korrekt und vollständig im Zielsystem angekommen sind, und erstellt einen Abweichungsreport.",
    phase: "Verification",
    agentType: "verification",
    color: "rose",
  },
  {
    id: "audit",
    title: "Audit Agent",
    description: "Dokumentiert jede Aktion, API-Request und Datenveränderung revisionssicher für Nachvollziehbarkeit und Compliance.",
    phase: "Audit",
    agentType: "audit",
    color: "sky",
  },
  {
    id: "feedback",
    title: "Feedback Agent",
    description: "Lernt aus durchgeführten Migrationen (manuellen Korrekturen, Fehlern, Feedback) und verbessert Mapping-Heuristiken automatisch.",
    phase: "Feedback",
    agentType: "feedback",
    color: "violet",
  },
] as const;
