export const AGENT_WORKFLOW_STEPS = [
  {
    id: "system-detection",
    title: "System Detection Agent",
    description: "Erkennt automatisch, welches System (z. B. Jira Cloud, Asana, Azure DevOps) hinter einer angegebenen URL steckt und welche API-Version verfügbar ist.",
    phase: "1. Discovery",
    agentType: "system-detection",
    color: "sky",
  },
  {
    id: "auth-flow",
    title: "Auth Flow Agent",
    description: "Leitet anhand des erkannten Systems den passenden Authentifizierungsprozess ein (API Token, OAuth2, Basic Auth etc.) und prüft die Berechtigungen.",
    phase: "2. Authentication",
    agentType: "auth-flow",
    color: "violet",
  },
  {
    id: "schema-discovery",
    title: "Schema Discovery Agent",
    description: "Ermittelt alle verfügbaren Datenobjekte und Felder im Quellsystem (z. B. Issues, Projects, Users) durch strukturierte API-Probes.",
    phase: "3. Capability Analysis",
    agentType: "schema-discovery",
    color: "emerald",
  },
  {
    id: "model-mapping",
    title: "Model Mapping Agent",
    description: "Ordnet die erkannten Datenfelder des Quellsystems dem Celion-Meta-Modell zu, um eine standardisierte interne Repräsentation zu erzeugen.",
    phase: "4. Meta-Model Alignment",
    agentType: "model-mapping",
    color: "amber",
  },
  {
    id: "target-schema",
    title: "Target Schema Agent",
    description: "Analysiert das Zielsystem (z. B. Asana) und identifiziert, wie dessen Felder mit dem Celion-Meta-Modell kompatibel sind.",
    phase: "5. Target Preparation",
    agentType: "target-schema",
    color: "rose",
  },
  {
    id: "mapping-suggestion",
    title: "Mapping Suggestion Agent",
    description: "Erstellt ein initiales Feld-zu-Feld-Mapping (Source → Target) basierend auf Ähnlichkeit, Bezeichnung, Typ und Kontext der Daten.",
    phase: "6. Auto-Mapping",
    agentType: "mapping-suggestion",
    color: "sky",
  },
  {
    id: "consistency-validation",
    title: "Consistency & Validation Agent",
    description: "Überprüft das vorgeschlagene Mapping auf Typinkonsistenzen, Pflichtfelder und mögliche Datenverluste.",
    phase: "7. Validation",
    agentType: "consistency-validation",
    color: "violet",
  },
  {
    id: "dry-run",
    title: "Dry-Run Agent",
    description: "Führt eine Simulation der Migration durch (ohne zu schreiben), um Fehler, leere Felder oder API-Limits frühzeitig zu erkennen.",
    phase: "8. Simulation",
    agentType: "dry-run",
    color: "emerald",
  },
  {
    id: "data-transfer",
    title: "Data Transfer Agent",
    description: "Führt die eigentliche Datenmigration aus, orchestriert Requests, Batch-Verarbeitung und Error-Recovery.",
    phase: "9. Execution",
    agentType: "data-transfer",
    color: "amber",
  },
  {
    id: "verification",
    title: "Verification Agent",
    description: "Prüft, ob alle Objekte korrekt und vollständig im Zielsystem angekommen sind, und erstellt einen Abweichungsreport.",
    phase: "10. Post-Migration",
    agentType: "verification",
    color: "rose",
  },
  {
    id: "audit",
    title: "Audit Agent",
    description: "Dokumentiert jede Aktion, API-Request und Datenveränderung revisionssicher für Nachvollziehbarkeit und Compliance.",
    phase: "11. Audit & Logging",
    agentType: "audit",
    color: "sky",
  },
  {
    id: "feedback",
    title: "Feedback Agent",
    description: "Lernt aus durchgeführten Migrationen (manuellen Korrekturen, Fehlern, Feedback) und verbessert Mapping-Heuristiken automatisch.",
    phase: "12. Optimization & Learning",
    agentType: "feedback",
    color: "violet",
  },
] as const;
