export const DATA_SOURCE_TYPE_OPTIONS = [
  "Jira Server",
  "Jira Data Center",
  "Azure DevOps Server (früher TFS)",
  "GitLab (Self-Managed Edition)",
  "GitHub Enterprise Server",
  "Redmine",
  "OpenProject",
  "Taiga",
  "YouTrack (Self-Hosted)",
  "Targetprocess",
  "Planisware",
  "Tuleap",
  "Trac",
  "Phabricator",
  "Bugzilla",
  "MantisBT",
  "Easy Redmine",
  "Odoo Project",
  "ClickUp",
  "Wrike Enterprise",
  "Monday.com",
  "Smartsheet",
  "Asana",
  "Trello",
  "Notion",
  "Basecamp",
  "Celoxis",
  "Orangescrum",
  "Zoho Projects",
  "ProjeQtOr",
  "Hansoft",
  "Rational Team Concert",
  "Polarion ALM",
  "Micro Focus ALM / Octane",
  "SAP Project System",
  "HP Project and Portfolio Management",
  "Clarizen One",
  "Sciforma",
  "Leankit",
  "MeisterTask",
  "Airtable",
] as const;

export type DataSourceType = (typeof DATA_SOURCE_TYPE_OPTIONS)[number];
